# apiVersion: v1
# kind: Namespace
# metadata:
#   name: db-base
# ---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql
  labels:
    name: pv-postgresql
  namespace: db-base
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.200
    path: "/root/data/postgresql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgresql
  namespace: db-base
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: pv-postgresql
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: postgresql-config
#   namespace: db-base
#   labels:
#     app: postgresql
# data:
#   POSTGRES_DB: "gitlab_production"
#   POSTGRES_USER: "gitlab"
#   POSTGRES_PASSWORD: "123456"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: db-base
  labels:
    name: postgresql
spec:
  selector:
      matchLabels:
        app: postgresql
  template:
    metadata:
      name: postgresql
      labels:
        name: postgresql
        app: postgresql
      namespace: db-base
    spec:
      containers:
      - name: postgresql
        image: sameersbn/postgresql:10
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_USER
          value: "gitlab"
        - name: DB_PASS
          value: "123456"
        - name: DB_NAME
          value: "gitlab_production"
        - name: DB_EXTENSION
          value: "pg_trgm"
        - name: NAMI_LOG_LEVEL
          value: "trace"
        ports:
        - name: postgresql
          containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: nfs
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: pvc-postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: db-base
  labels:
    name: postgresql
spec:
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    name: postgresql