apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-drone
  labels:
    app: pv-drone
  namespace: kube-ops
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.200
    path: "/root/data/drone"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-drone
  namespace: kube-ops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: pv-drone