apiVersion: v1
kind: Service
metadata:
  name: bazel-remote
  namespace: cicd
  labels:
    name: bazel-remote
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: grpc
      port: 9092
      targetPort: grpc
  selector:
    name: bazel-remote