apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-bazel-remote
  namespace: cicd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: datalayer-nfs