apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis
  namespace: cicd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: datalayer-nfs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: cicd
  labels: 
    name: redis
spec:
  podManagementPolicy: Parallel
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        name: redis
        app: redis
      namespace: cicd
    spec:
      containers:
      - name: redis
        image: sameersbn/redis
        imagePullPolicy: IfNotPresent
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
          - mountPath: /var/lib/redis
            name: nfs
        livenessProbe:
          exec: 
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: pvc-redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: cicd
  labels:
    name: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    name: redis
